import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQuery from "@/providers/rct-query";
import { HydrationBoundary } from "@tanstack/react-query";
import { Toaster } from "sonner";
import { ErrorSuppressor } from "@/components/error-suppressor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <HydrationBoundary
          state={pageProps.dehydratedState}
        ></HydrationBoundary> */}
        <ErrorSuppressor />
        <Toaster />
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  );
}
